### ISSUE TITLE
Typo in the solution of Q1 in the radioactive.ipynb notebook

### ISSUE THREAD

**Issue by msadiq074** [cambridge-mlg/mphil-intro-module#4]
Greetings

In the solution of the Q1) a) the exponent terms were compared to a new gaussian form coefficient. Unfortunately the terms don't add up to be the same and hence they can't be represented in a new Gaussian Format. Please have a look at the image given below
![image](https://user-images.githubusercontent.com/46165070/185815356-d1b7e664-0051-4492-83f4-9b54b92e6eb1.png)

Its a small typo and doesn't change the further questions. It would be correct if the answer was kept in the original terms before replacing it with Gaussian coefficients.

**Comment by ret26** [comment]
Thanks for the message.

I think that you are talking about Q2a here rather than Q1a.

Note that the solution says that the left hand side is *proportional* to
the right hand side, not equal. The constant of proportionality deals with
the issue that you identify.

All the best,
Rich

**Comment by msadiq074** [comment]
Thanks a lot for clearing my doubt. I completely missed the term of constant of proportionality. That does help in reducing the equation down to the Gaussian format. 

Thanks a lot for the quick response

Sincerely
Mohd Sadiq
